#cloud-config
packages-upgrade: true

runcmd:
  
  - rpm -Uvh --nosignature https://repo.zabbix.com/zabbix/6.0/sles/15/x86_64/zabbix-release-6.0-3.sles15.noarch.rpm
  - zypper --gpg-auto-import-keys refresh 'Zabbix Official Repository'
  - zypper in -y zabbix-server-mysql zabbix-web-mysql zabbix-apache-conf zabbix-sql-scripts zabbix-agent
  - zypper update -y --auto-agree-with-licenses
